version: '3.8'

services:
  app:
    build: .
    command: yarn dev --port 5173 --host 0.0.0.0
    container_name: cave-marc-et-seb
    ports:
      - "3002:5173"
    volumes:
      - .:/app
    working_dir: /app
    stdin_open: true
    tty: true
